# I/O Parameters

train_src_path: "data/train.src"
train_tgt_path: "data/train.tgt" 
train_metadata_path: "data/train.metadata"
valid_src_path: "data/valid.src"
valid_tgt_path: "data/valid.tgt"
valid_metadata_path: "data/valid.metadata"
test_src_path: "data/test.src"
test_tgt_path: "data/test.tgt"
test_metadata_path: "data/test.metadata"

languages: "en-sv"
language_filter_str: '"src_lang": "en", "tgt_lang": "sv"'
output_directory: "models/en-sv-Transformer"

# model_name: "CNN"
requeue: False

# Network Parameters

model_dimension: 512
number_of_heads: 8
max_length: 1000
hidden_dimension: 2048
number_of_layers: 6
drop_probability: 0.1

# Optimization

learning_rate: 0.1
factor: 0.9
patience: 10
weight_decay: 0.0005
batch_size: 128
gradientAccumulation: 1
max_epochs: 1000
early_stopping: 15
num_workers: 4

# Logging
print_metric_window: 1000