name: run tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ubuntu-latestt
        python-version: "3.10"
        testsuite: "full"
    steps:
      - uses: actions/checkout@v2
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: install system dependencies (linux)
        if: runner.os == 'Linux'
        # only managed to install system dependencies on Linux runners
        run: |
          sudo apt update
          sudo apt install libgmp-dev libmpfr-dev libmpc-dev
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tox (linux)
        run: tox -e py-${{ matrix.testsuite }} -- --hypothesis-profile=ci
      
